//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AccountPullHistory = newAccountPullHistoryTable("public", "account_pull_history", "")

type accountPullHistoryTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	AccountID  postgres.ColumnString
	PackID     postgres.ColumnString
	CardID     postgres.ColumnString
	Rarity     postgres.ColumnString
	IsPity     postgres.ColumnBool
	IsFeatured postgres.ColumnBool
	IsNew      postgres.ColumnBool
	PulledAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AccountPullHistoryTable struct {
	accountPullHistoryTable

	EXCLUDED accountPullHistoryTable
}

// AS creates new AccountPullHistoryTable with assigned alias
func (a AccountPullHistoryTable) AS(alias string) *AccountPullHistoryTable {
	return newAccountPullHistoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AccountPullHistoryTable with assigned schema name
func (a AccountPullHistoryTable) FromSchema(schemaName string) *AccountPullHistoryTable {
	return newAccountPullHistoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AccountPullHistoryTable with assigned table prefix
func (a AccountPullHistoryTable) WithPrefix(prefix string) *AccountPullHistoryTable {
	return newAccountPullHistoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AccountPullHistoryTable with assigned table suffix
func (a AccountPullHistoryTable) WithSuffix(suffix string) *AccountPullHistoryTable {
	return newAccountPullHistoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAccountPullHistoryTable(schemaName, tableName, alias string) *AccountPullHistoryTable {
	return &AccountPullHistoryTable{
		accountPullHistoryTable: newAccountPullHistoryTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newAccountPullHistoryTableImpl("", "excluded", ""),
	}
}

func newAccountPullHistoryTableImpl(schemaName, tableName, alias string) accountPullHistoryTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		AccountIDColumn  = postgres.StringColumn("account_id")
		PackIDColumn     = postgres.StringColumn("pack_id")
		CardIDColumn     = postgres.StringColumn("card_id")
		RarityColumn     = postgres.StringColumn("rarity")
		IsPityColumn     = postgres.BoolColumn("is_pity")
		IsFeaturedColumn = postgres.BoolColumn("is_featured")
		IsNewColumn      = postgres.BoolColumn("is_new")
		PulledAtColumn   = postgres.TimestampzColumn("pulled_at")
		allColumns       = postgres.ColumnList{IDColumn, AccountIDColumn, PackIDColumn, CardIDColumn, RarityColumn, IsPityColumn, IsFeaturedColumn, IsNewColumn, PulledAtColumn}
		mutableColumns   = postgres.ColumnList{AccountIDColumn, PackIDColumn, CardIDColumn, RarityColumn, IsPityColumn, IsFeaturedColumn, IsNewColumn, PulledAtColumn}
		defaultColumns   = postgres.ColumnList{IDColumn, IsPityColumn, IsFeaturedColumn, IsNewColumn, PulledAtColumn}
	)

	return accountPullHistoryTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		AccountID:  AccountIDColumn,
		PackID:     PackIDColumn,
		CardID:     CardIDColumn,
		Rarity:     RarityColumn,
		IsPity:     IsPityColumn,
		IsFeatured: IsFeaturedColumn,
		IsNew:      IsNewColumn,
		PulledAt:   PulledAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
