//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AccountPackPity = newAccountPackPityTable("public", "account_pack_pity", "")

type accountPackPityTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	AccountID postgres.ColumnString
	PackID    postgres.ColumnString
	Rarity    postgres.ColumnString
	Counter   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AccountPackPityTable struct {
	accountPackPityTable

	EXCLUDED accountPackPityTable
}

// AS creates new AccountPackPityTable with assigned alias
func (a AccountPackPityTable) AS(alias string) *AccountPackPityTable {
	return newAccountPackPityTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AccountPackPityTable with assigned schema name
func (a AccountPackPityTable) FromSchema(schemaName string) *AccountPackPityTable {
	return newAccountPackPityTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AccountPackPityTable with assigned table prefix
func (a AccountPackPityTable) WithPrefix(prefix string) *AccountPackPityTable {
	return newAccountPackPityTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AccountPackPityTable with assigned table suffix
func (a AccountPackPityTable) WithSuffix(suffix string) *AccountPackPityTable {
	return newAccountPackPityTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAccountPackPityTable(schemaName, tableName, alias string) *AccountPackPityTable {
	return &AccountPackPityTable{
		accountPackPityTable: newAccountPackPityTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newAccountPackPityTableImpl("", "excluded", ""),
	}
}

func newAccountPackPityTableImpl(schemaName, tableName, alias string) accountPackPityTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		AccountIDColumn = postgres.StringColumn("account_id")
		PackIDColumn    = postgres.StringColumn("pack_id")
		RarityColumn    = postgres.StringColumn("rarity")
		CounterColumn   = postgres.IntegerColumn("counter")
		allColumns      = postgres.ColumnList{IDColumn, AccountIDColumn, PackIDColumn, RarityColumn, CounterColumn}
		mutableColumns  = postgres.ColumnList{AccountIDColumn, PackIDColumn, RarityColumn, CounterColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CounterColumn}
	)

	return accountPackPityTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		AccountID: AccountIDColumn,
		PackID:    PackIDColumn,
		Rarity:    RarityColumn,
		Counter:   CounterColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
