//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AccountCard = newAccountCardTable("public", "account_card", "")

type accountCardTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	AccountID  postgres.ColumnString
	CardID     postgres.ColumnString
	Level      postgres.ColumnInteger
	ObtainedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AccountCardTable struct {
	accountCardTable

	EXCLUDED accountCardTable
}

// AS creates new AccountCardTable with assigned alias
func (a AccountCardTable) AS(alias string) *AccountCardTable {
	return newAccountCardTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AccountCardTable with assigned schema name
func (a AccountCardTable) FromSchema(schemaName string) *AccountCardTable {
	return newAccountCardTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AccountCardTable with assigned table prefix
func (a AccountCardTable) WithPrefix(prefix string) *AccountCardTable {
	return newAccountCardTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AccountCardTable with assigned table suffix
func (a AccountCardTable) WithSuffix(suffix string) *AccountCardTable {
	return newAccountCardTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAccountCardTable(schemaName, tableName, alias string) *AccountCardTable {
	return &AccountCardTable{
		accountCardTable: newAccountCardTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newAccountCardTableImpl("", "excluded", ""),
	}
}

func newAccountCardTableImpl(schemaName, tableName, alias string) accountCardTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		AccountIDColumn  = postgres.StringColumn("account_id")
		CardIDColumn     = postgres.StringColumn("card_id")
		LevelColumn      = postgres.IntegerColumn("level")
		ObtainedAtColumn = postgres.TimestampzColumn("obtained_at")
		allColumns       = postgres.ColumnList{IDColumn, AccountIDColumn, CardIDColumn, LevelColumn, ObtainedAtColumn}
		mutableColumns   = postgres.ColumnList{AccountIDColumn, CardIDColumn, LevelColumn, ObtainedAtColumn}
		defaultColumns   = postgres.ColumnList{IDColumn, LevelColumn, ObtainedAtColumn}
	)

	return accountCardTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		AccountID:  AccountIDColumn,
		CardID:     CardIDColumn,
		Level:      LevelColumn,
		ObtainedAt: ObtainedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
