//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AccountBalance = newAccountBalanceTable("public", "account_balance", "")

type accountBalanceTable struct {
	postgres.Table

	// Columns
	AccountID postgres.ColumnString
	Coin      postgres.ColumnInteger
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AccountBalanceTable struct {
	accountBalanceTable

	EXCLUDED accountBalanceTable
}

// AS creates new AccountBalanceTable with assigned alias
func (a AccountBalanceTable) AS(alias string) *AccountBalanceTable {
	return newAccountBalanceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AccountBalanceTable with assigned schema name
func (a AccountBalanceTable) FromSchema(schemaName string) *AccountBalanceTable {
	return newAccountBalanceTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AccountBalanceTable with assigned table prefix
func (a AccountBalanceTable) WithPrefix(prefix string) *AccountBalanceTable {
	return newAccountBalanceTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AccountBalanceTable with assigned table suffix
func (a AccountBalanceTable) WithSuffix(suffix string) *AccountBalanceTable {
	return newAccountBalanceTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAccountBalanceTable(schemaName, tableName, alias string) *AccountBalanceTable {
	return &AccountBalanceTable{
		accountBalanceTable: newAccountBalanceTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newAccountBalanceTableImpl("", "excluded", ""),
	}
}

func newAccountBalanceTableImpl(schemaName, tableName, alias string) accountBalanceTable {
	var (
		AccountIDColumn = postgres.StringColumn("account_id")
		CoinColumn      = postgres.IntegerColumn("coin")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{AccountIDColumn, CoinColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CoinColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{CoinColumn, UpdatedAtColumn}
	)

	return accountBalanceTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		AccountID: AccountIDColumn,
		Coin:      CoinColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
