//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Anime = newAnimeTable("public", "anime", "")

type animeTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnString
	MalID      postgres.ColumnInteger
	Title      postgres.ColumnString
	Synopsis   postgres.ColumnString
	CoverImage postgres.ColumnString
	CreatedAt  postgres.ColumnTimestampz
	UpdatedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AnimeTable struct {
	animeTable

	EXCLUDED animeTable
}

// AS creates new AnimeTable with assigned alias
func (a AnimeTable) AS(alias string) *AnimeTable {
	return newAnimeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AnimeTable with assigned schema name
func (a AnimeTable) FromSchema(schemaName string) *AnimeTable {
	return newAnimeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AnimeTable with assigned table prefix
func (a AnimeTable) WithPrefix(prefix string) *AnimeTable {
	return newAnimeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AnimeTable with assigned table suffix
func (a AnimeTable) WithSuffix(suffix string) *AnimeTable {
	return newAnimeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAnimeTable(schemaName, tableName, alias string) *AnimeTable {
	return &AnimeTable{
		animeTable: newAnimeTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newAnimeTableImpl("", "excluded", ""),
	}
}

func newAnimeTableImpl(schemaName, tableName, alias string) animeTable {
	var (
		IDColumn         = postgres.StringColumn("id")
		MalIDColumn      = postgres.IntegerColumn("mal_id")
		TitleColumn      = postgres.StringColumn("title")
		SynopsisColumn   = postgres.StringColumn("synopsis")
		CoverImageColumn = postgres.StringColumn("cover_image")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampzColumn("updated_at")
		allColumns       = postgres.ColumnList{IDColumn, MalIDColumn, TitleColumn, SynopsisColumn, CoverImageColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{MalIDColumn, TitleColumn, SynopsisColumn, CoverImageColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return animeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		MalID:      MalIDColumn,
		Title:      TitleColumn,
		Synopsis:   SynopsisColumn,
		CoverImage: CoverImageColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
