//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CardTag = newCardTagTable("public", "card_tag", "")

type cardTagTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Name      postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CardTagTable struct {
	cardTagTable

	EXCLUDED cardTagTable
}

// AS creates new CardTagTable with assigned alias
func (a CardTagTable) AS(alias string) *CardTagTable {
	return newCardTagTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CardTagTable with assigned schema name
func (a CardTagTable) FromSchema(schemaName string) *CardTagTable {
	return newCardTagTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CardTagTable with assigned table prefix
func (a CardTagTable) WithPrefix(prefix string) *CardTagTable {
	return newCardTagTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CardTagTable with assigned table suffix
func (a CardTagTable) WithSuffix(suffix string) *CardTagTable {
	return newCardTagTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCardTagTable(schemaName, tableName, alias string) *CardTagTable {
	return &CardTagTable{
		cardTagTable: newCardTagTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newCardTagTableImpl("", "excluded", ""),
	}
}

func newCardTagTableImpl(schemaName, tableName, alias string) cardTagTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return cardTagTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
