//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Card = newCardTable("public", "card", "")

type cardTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	MalID     postgres.ColumnInteger
	AnimeID   postgres.ColumnString
	RarityID  postgres.ColumnString
	Name      postgres.ColumnString
	Image     postgres.ColumnString
	Config    postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CardTable struct {
	cardTable

	EXCLUDED cardTable
}

// AS creates new CardTable with assigned alias
func (a CardTable) AS(alias string) *CardTable {
	return newCardTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CardTable with assigned schema name
func (a CardTable) FromSchema(schemaName string) *CardTable {
	return newCardTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CardTable with assigned table prefix
func (a CardTable) WithPrefix(prefix string) *CardTable {
	return newCardTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CardTable with assigned table suffix
func (a CardTable) WithSuffix(suffix string) *CardTable {
	return newCardTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCardTable(schemaName, tableName, alias string) *CardTable {
	return &CardTable{
		cardTable: newCardTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newCardTableImpl("", "excluded", ""),
	}
}

func newCardTableImpl(schemaName, tableName, alias string) cardTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		MalIDColumn     = postgres.IntegerColumn("mal_id")
		AnimeIDColumn   = postgres.StringColumn("anime_id")
		RarityIDColumn  = postgres.StringColumn("rarity_id")
		NameColumn      = postgres.StringColumn("name")
		ImageColumn     = postgres.StringColumn("image")
		ConfigColumn    = postgres.StringColumn("config")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, MalIDColumn, AnimeIDColumn, RarityIDColumn, NameColumn, ImageColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{MalIDColumn, AnimeIDColumn, RarityIDColumn, NameColumn, ImageColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return cardTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		MalID:     MalIDColumn,
		AnimeID:   AnimeIDColumn,
		RarityID:  RarityIDColumn,
		Name:      NameColumn,
		Image:     ImageColumn,
		Config:    ConfigColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
