//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CheckInRecord = newCheckInRecordTable("public", "check_in_record", "")

type checkInRecordTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	AccountID   postgres.ColumnString
	PlanID      postgres.ColumnString
	ClaimCount  postgres.ColumnInteger
	Streak      postgres.ColumnInteger
	LastClaimed postgres.ColumnTimestampz
	ResetAt     postgres.ColumnTimestampz
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CheckInRecordTable struct {
	checkInRecordTable

	EXCLUDED checkInRecordTable
}

// AS creates new CheckInRecordTable with assigned alias
func (a CheckInRecordTable) AS(alias string) *CheckInRecordTable {
	return newCheckInRecordTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CheckInRecordTable with assigned schema name
func (a CheckInRecordTable) FromSchema(schemaName string) *CheckInRecordTable {
	return newCheckInRecordTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CheckInRecordTable with assigned table prefix
func (a CheckInRecordTable) WithPrefix(prefix string) *CheckInRecordTable {
	return newCheckInRecordTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CheckInRecordTable with assigned table suffix
func (a CheckInRecordTable) WithSuffix(suffix string) *CheckInRecordTable {
	return newCheckInRecordTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCheckInRecordTable(schemaName, tableName, alias string) *CheckInRecordTable {
	return &CheckInRecordTable{
		checkInRecordTable: newCheckInRecordTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newCheckInRecordTableImpl("", "excluded", ""),
	}
}

func newCheckInRecordTableImpl(schemaName, tableName, alias string) checkInRecordTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		AccountIDColumn   = postgres.StringColumn("account_id")
		PlanIDColumn      = postgres.StringColumn("plan_id")
		ClaimCountColumn  = postgres.IntegerColumn("claim_count")
		StreakColumn      = postgres.IntegerColumn("streak")
		LastClaimedColumn = postgres.TimestampzColumn("last_claimed")
		ResetAtColumn     = postgres.TimestampzColumn("reset_at")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, AccountIDColumn, PlanIDColumn, ClaimCountColumn, StreakColumn, LastClaimedColumn, ResetAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{AccountIDColumn, PlanIDColumn, ClaimCountColumn, StreakColumn, LastClaimedColumn, ResetAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, ClaimCountColumn, StreakColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return checkInRecordTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		AccountID:   AccountIDColumn,
		PlanID:      PlanIDColumn,
		ClaimCount:  ClaimCountColumn,
		Streak:      StreakColumn,
		LastClaimed: LastClaimedColumn,
		ResetAt:     ResetAtColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
