//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CheckInPlan = newCheckInPlanTable("public", "check_in_plan", "")

type checkInPlanTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Code        postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString
	Type        postgres.ColumnString
	Interval    postgres.ColumnInteger
	MaxClaims   postgres.ColumnInteger
	Rewards     postgres.ColumnString
	ResetPolicy postgres.ColumnString
	IsActive    postgres.ColumnBool
	StartsAt    postgres.ColumnTimestampz
	EndsAt      postgres.ColumnTimestampz
	SortOrder   postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CheckInPlanTable struct {
	checkInPlanTable

	EXCLUDED checkInPlanTable
}

// AS creates new CheckInPlanTable with assigned alias
func (a CheckInPlanTable) AS(alias string) *CheckInPlanTable {
	return newCheckInPlanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CheckInPlanTable with assigned schema name
func (a CheckInPlanTable) FromSchema(schemaName string) *CheckInPlanTable {
	return newCheckInPlanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CheckInPlanTable with assigned table prefix
func (a CheckInPlanTable) WithPrefix(prefix string) *CheckInPlanTable {
	return newCheckInPlanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CheckInPlanTable with assigned table suffix
func (a CheckInPlanTable) WithSuffix(suffix string) *CheckInPlanTable {
	return newCheckInPlanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCheckInPlanTable(schemaName, tableName, alias string) *CheckInPlanTable {
	return &CheckInPlanTable{
		checkInPlanTable: newCheckInPlanTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newCheckInPlanTableImpl("", "excluded", ""),
	}
}

func newCheckInPlanTableImpl(schemaName, tableName, alias string) checkInPlanTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		CodeColumn        = postgres.StringColumn("code")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		TypeColumn        = postgres.StringColumn("type")
		IntervalColumn    = postgres.IntegerColumn("interval")
		MaxClaimsColumn   = postgres.IntegerColumn("max_claims")
		RewardsColumn     = postgres.StringColumn("rewards")
		ResetPolicyColumn = postgres.StringColumn("reset_policy")
		IsActiveColumn    = postgres.BoolColumn("is_active")
		StartsAtColumn    = postgres.TimestampzColumn("starts_at")
		EndsAtColumn      = postgres.TimestampzColumn("ends_at")
		SortOrderColumn   = postgres.IntegerColumn("sort_order")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, CodeColumn, NameColumn, DescriptionColumn, TypeColumn, IntervalColumn, MaxClaimsColumn, RewardsColumn, ResetPolicyColumn, IsActiveColumn, StartsAtColumn, EndsAtColumn, SortOrderColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{CodeColumn, NameColumn, DescriptionColumn, TypeColumn, IntervalColumn, MaxClaimsColumn, RewardsColumn, ResetPolicyColumn, IsActiveColumn, StartsAtColumn, EndsAtColumn, SortOrderColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, MaxClaimsColumn, IsActiveColumn, SortOrderColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return checkInPlanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Code:        CodeColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		Type:        TypeColumn,
		Interval:    IntervalColumn,
		MaxClaims:   MaxClaimsColumn,
		Rewards:     RewardsColumn,
		ResetPolicy: ResetPolicyColumn,
		IsActive:    IsActiveColumn,
		StartsAt:    StartsAtColumn,
		EndsAt:      EndsAtColumn,
		SortOrder:   SortOrderColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
