//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PackPool = newPackPoolTable("public", "pack_pool", "")

type packPoolTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	Name          postgres.ColumnString
	Description   postgres.ColumnString
	ActiveCount   postgres.ColumnInteger
	RotationDay   postgres.ColumnInteger
	LastRotatedAt postgres.ColumnTimestampz
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PackPoolTable struct {
	packPoolTable

	EXCLUDED packPoolTable
}

// AS creates new PackPoolTable with assigned alias
func (a PackPoolTable) AS(alias string) *PackPoolTable {
	return newPackPoolTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PackPoolTable with assigned schema name
func (a PackPoolTable) FromSchema(schemaName string) *PackPoolTable {
	return newPackPoolTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PackPoolTable with assigned table prefix
func (a PackPoolTable) WithPrefix(prefix string) *PackPoolTable {
	return newPackPoolTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PackPoolTable with assigned table suffix
func (a PackPoolTable) WithSuffix(suffix string) *PackPoolTable {
	return newPackPoolTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPackPoolTable(schemaName, tableName, alias string) *PackPoolTable {
	return &PackPoolTable{
		packPoolTable: newPackPoolTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newPackPoolTableImpl("", "excluded", ""),
	}
}

func newPackPoolTableImpl(schemaName, tableName, alias string) packPoolTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		NameColumn          = postgres.StringColumn("name")
		DescriptionColumn   = postgres.StringColumn("description")
		ActiveCountColumn   = postgres.IntegerColumn("active_count")
		RotationDayColumn   = postgres.IntegerColumn("rotation_day")
		LastRotatedAtColumn = postgres.TimestampzColumn("last_rotated_at")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, ActiveCountColumn, RotationDayColumn, LastRotatedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{NameColumn, DescriptionColumn, ActiveCountColumn, RotationDayColumn, LastRotatedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, ActiveCountColumn, RotationDayColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return packPoolTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		Name:          NameColumn,
		Description:   DescriptionColumn,
		ActiveCount:   ActiveCountColumn,
		RotationDay:   RotationDayColumn,
		LastRotatedAt: LastRotatedAtColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
