//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PackPool = newPackPoolTable("public", "pack_pool", "")

type packPoolTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	Name              postgres.ColumnString
	Description       postgres.ColumnString
	ActiveCount       postgres.ColumnInteger
	RotationDay       postgres.ColumnInteger
	LastRotatedAt     postgres.ColumnTimestampz
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz
	Image             postgres.ColumnString
	BannerType        postgres.ColumnString
	SortOrder         postgres.ColumnInteger
	IsActive          postgres.ColumnBool
	OpenAt            postgres.ColumnTimestampz
	CloseAt           postgres.ColumnTimestampz
	RotationType      postgres.ColumnString
	RotationInterval  postgres.ColumnInteger
	RotationHour      postgres.ColumnInteger
	RotationOrderMode postgres.ColumnString
	NextRotationAt    postgres.ColumnTimestampz
	PreviewDays       postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PackPoolTable struct {
	packPoolTable

	EXCLUDED packPoolTable
}

// AS creates new PackPoolTable with assigned alias
func (a PackPoolTable) AS(alias string) *PackPoolTable {
	return newPackPoolTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PackPoolTable with assigned schema name
func (a PackPoolTable) FromSchema(schemaName string) *PackPoolTable {
	return newPackPoolTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PackPoolTable with assigned table prefix
func (a PackPoolTable) WithPrefix(prefix string) *PackPoolTable {
	return newPackPoolTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PackPoolTable with assigned table suffix
func (a PackPoolTable) WithSuffix(suffix string) *PackPoolTable {
	return newPackPoolTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPackPoolTable(schemaName, tableName, alias string) *PackPoolTable {
	return &PackPoolTable{
		packPoolTable: newPackPoolTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newPackPoolTableImpl("", "excluded", ""),
	}
}

func newPackPoolTableImpl(schemaName, tableName, alias string) packPoolTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		NameColumn              = postgres.StringColumn("name")
		DescriptionColumn       = postgres.StringColumn("description")
		ActiveCountColumn       = postgres.IntegerColumn("active_count")
		RotationDayColumn       = postgres.IntegerColumn("rotation_day")
		LastRotatedAtColumn     = postgres.TimestampzColumn("last_rotated_at")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		ImageColumn             = postgres.StringColumn("image")
		BannerTypeColumn        = postgres.StringColumn("banner_type")
		SortOrderColumn         = postgres.IntegerColumn("sort_order")
		IsActiveColumn          = postgres.BoolColumn("is_active")
		OpenAtColumn            = postgres.TimestampzColumn("open_at")
		CloseAtColumn           = postgres.TimestampzColumn("close_at")
		RotationTypeColumn      = postgres.StringColumn("rotation_type")
		RotationIntervalColumn  = postgres.IntegerColumn("rotation_interval")
		RotationHourColumn      = postgres.IntegerColumn("rotation_hour")
		RotationOrderModeColumn = postgres.StringColumn("rotation_order_mode")
		NextRotationAtColumn    = postgres.TimestampzColumn("next_rotation_at")
		PreviewDaysColumn       = postgres.IntegerColumn("preview_days")
		allColumns              = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, ActiveCountColumn, RotationDayColumn, LastRotatedAtColumn, CreatedAtColumn, UpdatedAtColumn, ImageColumn, BannerTypeColumn, SortOrderColumn, IsActiveColumn, OpenAtColumn, CloseAtColumn, RotationTypeColumn, RotationIntervalColumn, RotationHourColumn, RotationOrderModeColumn, NextRotationAtColumn, PreviewDaysColumn}
		mutableColumns          = postgres.ColumnList{NameColumn, DescriptionColumn, ActiveCountColumn, RotationDayColumn, LastRotatedAtColumn, CreatedAtColumn, UpdatedAtColumn, ImageColumn, BannerTypeColumn, SortOrderColumn, IsActiveColumn, OpenAtColumn, CloseAtColumn, RotationTypeColumn, RotationIntervalColumn, RotationHourColumn, RotationOrderModeColumn, NextRotationAtColumn, PreviewDaysColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, ActiveCountColumn, CreatedAtColumn, UpdatedAtColumn, BannerTypeColumn, SortOrderColumn, IsActiveColumn, RotationTypeColumn, RotationIntervalColumn, RotationHourColumn, RotationOrderModeColumn, PreviewDaysColumn}
	)

	return packPoolTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		Name:              NameColumn,
		Description:       DescriptionColumn,
		ActiveCount:       ActiveCountColumn,
		RotationDay:       RotationDayColumn,
		LastRotatedAt:     LastRotatedAtColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,
		Image:             ImageColumn,
		BannerType:        BannerTypeColumn,
		SortOrder:         SortOrderColumn,
		IsActive:          IsActiveColumn,
		OpenAt:            OpenAtColumn,
		CloseAt:           CloseAtColumn,
		RotationType:      RotationTypeColumn,
		RotationInterval:  RotationIntervalColumn,
		RotationHour:      RotationHourColumn,
		RotationOrderMode: RotationOrderModeColumn,
		NextRotationAt:    NextRotationAtColumn,
		PreviewDays:       PreviewDaysColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
