//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PackCard = newPackCardTable("public", "pack_card", "")

type packCardTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	PackID       postgres.ColumnString
	CardID       postgres.ColumnString
	Weight       postgres.ColumnFloat
	IsFeatured   postgres.ColumnBool
	FeaturedRate postgres.ColumnFloat

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PackCardTable struct {
	packCardTable

	EXCLUDED packCardTable
}

// AS creates new PackCardTable with assigned alias
func (a PackCardTable) AS(alias string) *PackCardTable {
	return newPackCardTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PackCardTable with assigned schema name
func (a PackCardTable) FromSchema(schemaName string) *PackCardTable {
	return newPackCardTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PackCardTable with assigned table prefix
func (a PackCardTable) WithPrefix(prefix string) *PackCardTable {
	return newPackCardTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PackCardTable with assigned table suffix
func (a PackCardTable) WithSuffix(suffix string) *PackCardTable {
	return newPackCardTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPackCardTable(schemaName, tableName, alias string) *PackCardTable {
	return &PackCardTable{
		packCardTable: newPackCardTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newPackCardTableImpl("", "excluded", ""),
	}
}

func newPackCardTableImpl(schemaName, tableName, alias string) packCardTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		PackIDColumn       = postgres.StringColumn("pack_id")
		CardIDColumn       = postgres.StringColumn("card_id")
		WeightColumn       = postgres.FloatColumn("weight")
		IsFeaturedColumn   = postgres.BoolColumn("is_featured")
		FeaturedRateColumn = postgres.FloatColumn("featured_rate")
		allColumns         = postgres.ColumnList{IDColumn, PackIDColumn, CardIDColumn, WeightColumn, IsFeaturedColumn, FeaturedRateColumn}
		mutableColumns     = postgres.ColumnList{PackIDColumn, CardIDColumn, WeightColumn, IsFeaturedColumn, FeaturedRateColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, WeightColumn, IsFeaturedColumn}
	)

	return packCardTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		PackID:       PackIDColumn,
		CardID:       CardIDColumn,
		Weight:       WeightColumn,
		IsFeatured:   IsFeaturedColumn,
		FeaturedRate: FeaturedRateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
