//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Pack = newPackTable("public", "pack", "")

type packTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	Name                postgres.ColumnString
	Description         postgres.ColumnString
	Image               postgres.ColumnString
	CardsPerPull        postgres.ColumnInteger
	Config              postgres.ColumnString
	CreatedAt           postgres.ColumnTimestampz
	UpdatedAt           postgres.ColumnTimestampz
	Code                postgres.ColumnString
	NameImage           postgres.ColumnString
	SortOrder           postgres.ColumnInteger
	PoolID              postgres.ColumnString
	LastPoolActivatedAt postgres.ColumnTimestampz
	RotationOrder       postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PackTable struct {
	packTable

	EXCLUDED packTable
}

// AS creates new PackTable with assigned alias
func (a PackTable) AS(alias string) *PackTable {
	return newPackTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PackTable with assigned schema name
func (a PackTable) FromSchema(schemaName string) *PackTable {
	return newPackTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PackTable with assigned table prefix
func (a PackTable) WithPrefix(prefix string) *PackTable {
	return newPackTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PackTable with assigned table suffix
func (a PackTable) WithSuffix(suffix string) *PackTable {
	return newPackTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPackTable(schemaName, tableName, alias string) *PackTable {
	return &PackTable{
		packTable: newPackTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newPackTableImpl("", "excluded", ""),
	}
}

func newPackTableImpl(schemaName, tableName, alias string) packTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		NameColumn                = postgres.StringColumn("name")
		DescriptionColumn         = postgres.StringColumn("description")
		ImageColumn               = postgres.StringColumn("image")
		CardsPerPullColumn        = postgres.IntegerColumn("cards_per_pull")
		ConfigColumn              = postgres.StringColumn("config")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn           = postgres.TimestampzColumn("updated_at")
		CodeColumn                = postgres.StringColumn("code")
		NameImageColumn           = postgres.StringColumn("name_image")
		SortOrderColumn           = postgres.IntegerColumn("sort_order")
		PoolIDColumn              = postgres.StringColumn("pool_id")
		LastPoolActivatedAtColumn = postgres.TimestampzColumn("last_pool_activated_at")
		RotationOrderColumn       = postgres.IntegerColumn("rotation_order")
		allColumns                = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, ImageColumn, CardsPerPullColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn, CodeColumn, NameImageColumn, SortOrderColumn, PoolIDColumn, LastPoolActivatedAtColumn, RotationOrderColumn}
		mutableColumns            = postgres.ColumnList{NameColumn, DescriptionColumn, ImageColumn, CardsPerPullColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn, CodeColumn, NameImageColumn, SortOrderColumn, PoolIDColumn, LastPoolActivatedAtColumn, RotationOrderColumn}
		defaultColumns            = postgres.ColumnList{IDColumn, CardsPerPullColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn, CodeColumn, SortOrderColumn}
	)

	return packTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		Name:                NameColumn,
		Description:         DescriptionColumn,
		Image:               ImageColumn,
		CardsPerPull:        CardsPerPullColumn,
		Config:              ConfigColumn,
		CreatedAt:           CreatedAtColumn,
		UpdatedAt:           UpdatedAtColumn,
		Code:                CodeColumn,
		NameImage:           NameImageColumn,
		SortOrder:           SortOrderColumn,
		PoolID:              PoolIDColumn,
		LastPoolActivatedAt: LastPoolActivatedAtColumn,
		RotationOrder:       RotationOrderColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
