//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Profile = newProfileTable("public", "profile", "")

type profileTable struct {
	postgres.Table

	// Columns
	AccountID     postgres.ColumnString
	DisplayName   postgres.ColumnString
	Bio           postgres.ColumnString
	ShowcaseCards postgres.ColumnString
	UpdatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ProfileTable struct {
	profileTable

	EXCLUDED profileTable
}

// AS creates new ProfileTable with assigned alias
func (a ProfileTable) AS(alias string) *ProfileTable {
	return newProfileTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProfileTable with assigned schema name
func (a ProfileTable) FromSchema(schemaName string) *ProfileTable {
	return newProfileTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProfileTable with assigned table prefix
func (a ProfileTable) WithPrefix(prefix string) *ProfileTable {
	return newProfileTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProfileTable with assigned table suffix
func (a ProfileTable) WithSuffix(suffix string) *ProfileTable {
	return newProfileTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProfileTable(schemaName, tableName, alias string) *ProfileTable {
	return &ProfileTable{
		profileTable: newProfileTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newProfileTableImpl("", "excluded", ""),
	}
}

func newProfileTableImpl(schemaName, tableName, alias string) profileTable {
	var (
		AccountIDColumn     = postgres.StringColumn("account_id")
		DisplayNameColumn   = postgres.StringColumn("display_name")
		BioColumn           = postgres.StringColumn("bio")
		ShowcaseCardsColumn = postgres.StringColumn("showcase_cards")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		allColumns          = postgres.ColumnList{AccountIDColumn, DisplayNameColumn, BioColumn, ShowcaseCardsColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{DisplayNameColumn, BioColumn, ShowcaseCardsColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{ShowcaseCardsColumn, UpdatedAtColumn}
	)

	return profileTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		AccountID:     AccountIDColumn,
		DisplayName:   DisplayNameColumn,
		Bio:           BioColumn,
		ShowcaseCards: ShowcaseCardsColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
