//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Rarity = newRarityTable("public", "rarity", "")

type rarityTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Name      postgres.ColumnString
	Config    postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type RarityTable struct {
	rarityTable

	EXCLUDED rarityTable
}

// AS creates new RarityTable with assigned alias
func (a RarityTable) AS(alias string) *RarityTable {
	return newRarityTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RarityTable with assigned schema name
func (a RarityTable) FromSchema(schemaName string) *RarityTable {
	return newRarityTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RarityTable with assigned table prefix
func (a RarityTable) WithPrefix(prefix string) *RarityTable {
	return newRarityTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RarityTable with assigned table suffix
func (a RarityTable) WithSuffix(suffix string) *RarityTable {
	return newRarityTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRarityTable(schemaName, tableName, alias string) *RarityTable {
	return &RarityTable{
		rarityTable: newRarityTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newRarityTableImpl("", "excluded", ""),
	}
}

func newRarityTableImpl(schemaName, tableName, alias string) rarityTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		NameColumn      = postgres.StringColumn("name")
		ConfigColumn    = postgres.StringColumn("config")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return rarityTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		Config:    ConfigColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
