//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Account = Account.FromSchema(schema)
	AccountCard = AccountCard.FromSchema(schema)
	AccountPackPity = AccountPackPity.FromSchema(schema)
	AccountPullHistory = AccountPullHistory.FromSchema(schema)
	Anime = Anime.FromSchema(schema)
	Card = Card.FromSchema(schema)
	CardTag = CardTag.FromSchema(schema)
	Pack = Pack.FromSchema(schema)
	PackCard = PackCard.FromSchema(schema)
	PackPool = PackPool.FromSchema(schema)
}
