// Code generated by codegen; DO NOT EDIT.
package code

import (
	"net/http"

	"github.com/zakiverse/zakiverse-api/core/locale"
)

func init() {
	reg(AccountDiscordAuthFailed, Definition{
		StatusCode: http.StatusUnauthorized,
		Message: map[locale.Locale]string{
			locale.EN: "Discord authentication failed",
		},
	})
	reg(AccountCardAlreadyOwned, Definition{
		StatusCode: http.StatusConflict,
		Message: map[locale.Locale]string{
			locale.EN: "Account already owns this card",
		},
	})
	reg(AnimeAlreadyExists, Definition{
		StatusCode: http.StatusConflict,
		Message: map[locale.Locale]string{
			locale.EN: "Anime already exists",
		},
	})
	reg(AnimeDeleteHasCards, Definition{
		StatusCode: http.StatusConflict,
		Message: map[locale.Locale]string{
			locale.EN: "Cannot delete anime that has cards",
		},
	})
	reg(DefaultInvalidTimezone, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Invalid timezone",
		},
	})
	reg(DefaultParseUrl, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Failed to parse url",
		},
	})
	reg(HttpBadRequest, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Bad request",
		},
	})
	reg(HttpUnauthorized, Definition{
		StatusCode: http.StatusUnauthorized,
		Message: map[locale.Locale]string{
			locale.EN: "Unauthorized",
		},
	})
	reg(HttpForbidden, Definition{
		StatusCode: http.StatusForbidden,
		Message: map[locale.Locale]string{
			locale.EN: "Forbidden",
		},
	})
	reg(HttpNotFound, Definition{
		StatusCode: http.StatusNotFound,
		Message: map[locale.Locale]string{
			locale.EN: "Not found",
		},
	})
	reg(HttpConflict, Definition{
		StatusCode: http.StatusConflict,
		Message: map[locale.Locale]string{
			locale.EN: "Conflict",
		},
	})
	reg(HttpInternalServerError, Definition{
		StatusCode: http.StatusInternalServerError,
		Message: map[locale.Locale]string{
			locale.EN: "Internal server error",
		},
	})
	reg(ModelNotFound, Definition{
		StatusCode: http.StatusNotFound,
		Message: map[locale.Locale]string{
			locale.EN: "Data not found",
		},
	})
	reg(ErrorNotImplemented, Definition{
		StatusCode: http.StatusNotImplemented,
		Message: map[locale.Locale]string{
			locale.EN: "Error not implemented",
		},
	})
	reg(CardAlreadyExists, Definition{
		StatusCode: http.StatusConflict,
		Message: map[locale.Locale]string{
			locale.EN: "Card already exists",
		},
	})
	reg(PackNotActive, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Pack is not active",
		},
	})
	reg(BannerNotActive, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Banner is not active",
		},
	})
	reg(PackNotInRotation, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Pack is not in current rotation",
		},
	})
	reg(InsufficientCoins, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Insufficient coins",
		},
	})
	reg(CheckInTooEarly, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Cannot claim yet",
		},
	})
	reg(CheckInMaxReached, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Maximum claims reached",
		},
	})
	reg(CheckInPlanInactive, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Check-in plan is not active",
		},
	})
	reg(DisplayNameTaken, Definition{
		StatusCode: http.StatusConflict,
		Message: map[locale.Locale]string{
			locale.EN: "Display name is already taken",
		},
	})
	reg(ShowcaseCardNotOwned, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Showcase card not owned",
		},
	})
	reg(ShowcaseTooMany, Definition{
		StatusCode: http.StatusBadRequest,
		Message: map[locale.Locale]string{
			locale.EN: "Maximum 6 showcase cards",
		},
	})
}
