//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AccountRole string

const (
	AccountRole_User  AccountRole = "user"
	AccountRole_Admin AccountRole = "admin"
)

var AccountRoleAllValues = []AccountRole{
	AccountRole_User,
	AccountRole_Admin,
}

func (e *AccountRole) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "user":
		*e = AccountRole_User
	case "admin":
		*e = AccountRole_Admin
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AccountRole enum")
	}

	return nil
}

func (e AccountRole) String() string {
	return string(e)
}
