//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Anime struct {
	ID         uuid.UUID `sql:"primary_key"`
	MalID      int32
	Title      string
	Synopsis   *string
	CoverImage *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
