//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type BannerType string

const (
	BannerType_Standard BannerType = "standard"
	BannerType_Featured BannerType = "featured"
	BannerType_Event    BannerType = "event"
	BannerType_Beginner BannerType = "beginner"
	BannerType_Seasonal BannerType = "seasonal"
)

var BannerTypeAllValues = []BannerType{
	BannerType_Standard,
	BannerType_Featured,
	BannerType_Event,
	BannerType_Beginner,
	BannerType_Seasonal,
}

func (e *BannerType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "standard":
		*e = BannerType_Standard
	case "featured":
		*e = BannerType_Featured
	case "event":
		*e = BannerType_Event
	case "beginner":
		*e = BannerType_Beginner
	case "seasonal":
		*e = BannerType_Seasonal
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for BannerType enum")
	}

	return nil
}

func (e BannerType) String() string {
	return string(e)
}
