//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Card struct {
	ID        uuid.UUID `sql:"primary_key"`
	MalID     int32
	AnimeID   uuid.UUID
	Name      string
	Image     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Rarity    CardRarity
	Config    string
	TagID     uuid.UUID
	Favorite  int32
}
