//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type CardRarity string

const (
	CardRarity_Common    CardRarity = "common"
	CardRarity_Uncommon  CardRarity = "uncommon"
	CardRarity_Rare      CardRarity = "rare"
	CardRarity_Epic      CardRarity = "epic"
	CardRarity_Legendary CardRarity = "legendary"
	CardRarity_Prismatic CardRarity = "prismatic"
)

var CardRarityAllValues = []CardRarity{
	CardRarity_Common,
	CardRarity_Uncommon,
	CardRarity_Rare,
	CardRarity_Epic,
	CardRarity_Legendary,
	CardRarity_Prismatic,
}

func (e *CardRarity) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "common":
		*e = CardRarity_Common
	case "uncommon":
		*e = CardRarity_Uncommon
	case "rare":
		*e = CardRarity_Rare
	case "epic":
		*e = CardRarity_Epic
	case "legendary":
		*e = CardRarity_Legendary
	case "prismatic":
		*e = CardRarity_Prismatic
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for CardRarity enum")
	}

	return nil
}

func (e CardRarity) String() string {
	return string(e)
}
