//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CheckInType string

const (
	CheckInType_Recurring CheckInType = "recurring"
	CheckInType_Streak    CheckInType = "streak"
	CheckInType_Calendar  CheckInType = "calendar"
)
