//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CheckInResetPolicy string

const (
	CheckInResetPolicy_Rolling      CheckInResetPolicy = "rolling"
	CheckInResetPolicy_DailyReset   CheckInResetPolicy = "daily_reset"
	CheckInResetPolicy_WeeklyReset  CheckInResetPolicy = "weekly_reset"
	CheckInResetPolicy_MonthlyReset CheckInResetPolicy = "monthly_reset"
)
