//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type CheckInPlan struct {
	ID          uuid.UUID          `sql:"primary_key"`
	Code        string
	Name        string
	Description *string
	Type        CheckInType
	Interval    int32
	MaxClaims   int32
	Rewards     string
	ResetPolicy CheckInResetPolicy
	IsActive    bool
	StartsAt    *time.Time
	EndsAt      *time.Time
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
