//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Pack struct {
	ID                  uuid.UUID `sql:"primary_key"`
	Name                string
	Description         *string
	Image               string
	CardsPerPull        int32
	Config              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Code                string
	NameImage           *string
	SortOrder           int32
	PoolID              uuid.UUID
	LastPoolActivatedAt *time.Time
	RotationOrder       *int32
}
