//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PackPool struct {
	ID            uuid.UUID `sql:"primary_key"`
	Name          string
	Description   *string
	ActiveCount   int32
	RotationDay   int32
	LastRotatedAt *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
