//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PackType string

const (
	PackType_Standard PackType = "standard"
	PackType_Limited  PackType = "limited"
	PackType_Event    PackType = "event"
)

var PackTypeAllValues = []PackType{
	PackType_Standard,
	PackType_Limited,
	PackType_Event,
}

func (e *PackType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "standard":
		*e = PackType_Standard
	case "limited":
		*e = PackType_Limited
	case "event":
		*e = PackType_Event
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PackType enum")
	}

	return nil
}

func (e PackType) String() string {
	return string(e)
}
