//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type RotationType string

const (
	RotationType_None    RotationType = "none"
	RotationType_Weekly  RotationType = "weekly"
	RotationType_Monthly RotationType = "monthly"
)

var RotationTypeAllValues = []RotationType{
	RotationType_None,
	RotationType_Weekly,
	RotationType_Monthly,
}

func (e *RotationType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "none":
		*e = RotationType_None
	case "weekly":
		*e = RotationType_Weekly
	case "monthly":
		*e = RotationType_Monthly
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for RotationType enum")
	}

	return nil
}

func (e RotationType) String() string {
	return string(e)
}
