//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type RotationOrderMode string

const (
	RotationOrderMode_Auto   RotationOrderMode = "auto"
	RotationOrderMode_Manual RotationOrderMode = "manual"
)

var RotationOrderModeAllValues = []RotationOrderMode{
	RotationOrderMode_Auto,
	RotationOrderMode_Manual,
}

func (e *RotationOrderMode) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "auto":
		*e = RotationOrderMode_Auto
	case "manual":
		*e = RotationOrderMode_Manual
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for RotationOrderMode enum")
	}

	return nil
}

func (e RotationOrderMode) String() string {
	return string(e)
}
