//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var BannerType = &struct {
	Standard postgres.StringExpression
	Featured postgres.StringExpression
	Event    postgres.StringExpression
	Beginner postgres.StringExpression
	Seasonal postgres.StringExpression
}{
	Standard: postgres.NewEnumValue("standard"),
	Featured: postgres.NewEnumValue("featured"),
	Event:    postgres.NewEnumValue("event"),
	Beginner: postgres.NewEnumValue("beginner"),
	Seasonal: postgres.NewEnumValue("seasonal"),
}
