//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var CardRarity = &struct {
	Common    postgres.StringExpression
	Uncommon  postgres.StringExpression
	Rare      postgres.StringExpression
	Epic      postgres.StringExpression
	Legendary postgres.StringExpression
}{
	Common:    postgres.NewEnumValue("common"),
	Uncommon:  postgres.NewEnumValue("uncommon"),
	Rare:      postgres.NewEnumValue("rare"),
	Epic:      postgres.NewEnumValue("epic"),
	Legendary: postgres.NewEnumValue("legendary"),
}
