//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var CheckInResetPolicy = &struct {
	Rolling      postgres.StringExpression
	DailyReset   postgres.StringExpression
	WeeklyReset  postgres.StringExpression
	MonthlyReset postgres.StringExpression
}{
	Rolling:      postgres.NewEnumValue("rolling"),
	DailyReset:   postgres.NewEnumValue("daily_reset"),
	WeeklyReset:  postgres.NewEnumValue("weekly_reset"),
	MonthlyReset: postgres.NewEnumValue("monthly_reset"),
}
