//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var CheckInType = &struct {
	Recurring postgres.StringExpression
	Streak    postgres.StringExpression
	Calendar  postgres.StringExpression
}{
	Recurring: postgres.NewEnumValue("recurring"),
	Streak:    postgres.NewEnumValue("streak"),
	Calendar:  postgres.NewEnumValue("calendar"),
}
