//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var PackType = &struct {
	Standard postgres.StringExpression
	Limited  postgres.StringExpression
	Event    postgres.StringExpression
}{
	Standard: postgres.NewEnumValue("standard"),
	Limited:  postgres.NewEnumValue("limited"),
	Event:    postgres.NewEnumValue("event"),
}
