package main

import (
	"log"
	"path/filepath"
	"regexp"
	"text/template"

	"github.com/zakiverse/zakiverse-api/cmd/codegen"
)

var excludeFiles = map[string]bool{
	"error.go":     true,
	"generated.go": true,
}

var reHttp = regexp.MustCompile(`^//\s*@Http\s+(\S+)`)

var tmpl = template.Must(template.New("generated").Parse(`// Code generated by codegen; DO NOT EDIT.
package code

import (
	"net/http"

	"{{.Module}}/core/locale"
)

func init() {
{{- range .Entries -}}
	reg({{.Name}}, Definition{
		StatusCode: {{index .Tags "http"}},
		Message: map[locale.Locale]string{
{{- range .Messages}}
			locale.{{.Key}}: "{{.Value}}",
{{- end}}
		},
	})
{{end -}}
}
`))

type templateData struct {
	Module  string
	Entries []codegen.Entry
}

func main() {
	dir := codegen.ResolveDir("core/code")
	module := codegen.ReadModuleName()

	files := codegen.DiscoverFiles(dir, excludeFiles)
	if len(files) == 0 {
		log.Fatalf("no source .go files found in %s", dir)
	}

	cfg := codegen.ParserConfig{
		Dir:          dir,
		TypeName:     "Code",
		ExcludeFiles: excludeFiles,
		TagParsers: []codegen.TagParser{
			{
				Pattern: reHttp,
				Handler: func(entry *codegen.Entry, matches []string) {
					expr, err := codegen.ResolveHttpExpr(matches[1])
					if err != nil {
						log.Fatalf("constant %s: %v", entry.Name, err)
					}
					entry.Tags["http"] = expr
				},
			},
		},
	}

	entries := codegen.ParseFiles(files, cfg)

	for _, e := range entries {
		if e.Tags["http"] == "" {
			log.Fatalf("constant %s has @Locale but missing @Http annotation", e.Name)
		}
		if len(e.Messages) == 0 {
			log.Fatalf("constant %s has @Http but missing @Locale annotations", e.Name)
		}
	}

	codegen.Generate(codegen.GeneratorConfig{
		OutputFile: filepath.Join(dir, "generated.go"),
		Template:   tmpl,
		Data:       templateData{Module: module, Entries: entries},
	})
}
